services:
  master:
    build: ./master
    container_name: rl-master
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - SECONDARIES=http://secondary1:8001,http://secondary2:8001
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    depends_on:
      - secondary1
      - secondary2

  secondary1:
    build: ./secondary
    container_name: rl-secondary-1
    environment:
      - PORT=8001
      - DELAY_MS=0
      - LOG_LEVEL=INFO
    ports:
      - "8001:8001"

  secondary2:
    build: ./secondary
    container_name: rl-secondary-2
    environment:
      - PORT=8001
      - DELAY_MS=3000
      - LOG_LEVEL=INFO
    ports:
      - "8002:8001"
